In [1]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

RAW = Path("../data/raw/winemag-data-130k-v2.csv")

def load_data(filepath, dtypes=None):
    try:
        df = pd.read_csv(filepath, dtype=dtypes)
        print("✅ File loaded successfully.")
        print("🔍 Missing values per column:")
        print(df.isnull().sum())
        return df
    except Exception as e:
        print(f"❌ Error loading file: {e}")
        return None

In [2]:
df = load_data(RAW)
df.head()

✅ File loaded successfully.
🔍 Missing values per column:
Unnamed: 0                   0
country                     63
description                  0
designation              37465
points                       0
price                     8996
province                    63
region_1                 21247
region_2                 79460
taster_name              26244
taster_twitter_handle    31213
title                        0
variety                      1
winery                       0
dtype: int64

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [9]:
def summarise_df(df):
    num_cols,num_rows = df.shape
    print(f"🔢 Rows: {num_rows}, Columns: {num_cols}")

    missing_count = df.isnull().sum()
    missing_percent = (missing_count / len(df)) * 100

    unique_counts = df.nunique()

    summary = pd.DataFrame({
        'missing count' : missing_count,
        'missing %' : missing_percent.round(2),
        'unique Values' : unique_counts

    }).sort_values(by='missing %', ascending=False)

    return summary

In [10]:
summary_table = summarise_df(df)
summary_table.head(10)

🔢 Rows: 14, Columns: 129971

                       missing count  missing %  unique Values
region_2                       79460      61.14             17
designation                    37465      28.83          37979
taster_twitter_handle          31213      24.02             15
taster_name                    26244      20.19             19
region_1                       21247      16.35           1229
price                           8996       6.92            390
province                          63       0.05            425
country                           63       0.05             43
Unnamed: 0                         0       0.00         129971
description                        0       0.00         119955

In [11]:
def convert_type(df,schema):
    for column, dtype in schema.items():
        try:
            df[column] = df[column].astype(dtype)
            print(f'Convert {column} to {dtype}')
        except Exception as e:
            print(f"⚠️ Could not convert {column} to {dtype}: {e}")
    return df

In [12]:
schema ={
    'price':'float',
     'points': 'int',
    'country': 'string',
    'province': 'string',
    'variety': 'string'
}

df = convert_type(df,schema)

Convert price to float
Convert points to int
Convert country to string
Convert province to string
Convert variety to string

In [3]:
df.drop(columns=['region_2','taster_twitter_handle'],inplace=True)

In [8]:
median_price = df['price'].median()
df['price'] = df['price'].fillna(median_price)

mode_country = df['country'].mode()[0]
df['country'] = df['country'].fillna(mode_country)

mode_province = df['province'].mode()[0]
df['province'] = df['province'].fillna(mode_province)

mode_variety = df['variety'].mode()[0]
df['variety'] = df['variety'].fillna(mode_variety)

df['taster_name'] = df['taster_name'].fillna('Unknown')